---
- name: Automated Incident Remediation via ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    servicenow_instance: "{{ lookup('env', 'SN_INSTANCE') }}"
    servicenow_user: "{{ lookup('env', 'SN_USERNAME') }}"
    servicenow_password: "{{ lookup('env', 'SN_PASSWORD') }}"
    short_description: "Automated disk space alert"
    description: "Disk space exceeded 90% on host xyz.example.com"

  tasks:
    - name: Create incident in ServiceNow
      uri:
        url: "{{ SN_INSTANCE }}/api/now/table/incident"
        method: POST
        user: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        force_basic_auth: yes
        status_code: 201
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "{{ short_description }}"
          description: "{{ description }}"
      register: incident_response

    - name: Display created incident number
      debug:
        msg: "Created incident: {{ incident_response.json.result.number }}"
